server:
  port: 8082

spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/notification_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    consumer:
      group-id: booking-notification-group
    bootstrap-servers: localhost:9092

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}


booking-confirmed-topic: booking.confirmed.event