server:
  port: 8082

spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/notification_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  kafka:
    consumer:
      group-id: booking-notification-group
    bootstrap-servers: localhost:9092

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}
    test-chat-id: ${TELEGRAM_CHAT_ID:}


booking-confirmed-topic: booking.confirmed.event